version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: connect-redis
    versions:
    - ">= 5.a, < 6"
  - dependency-name: css-loader
    versions:
    - ">= 2.a, < 3"
  - dependency-name: css-loader
    versions:
    - ">= 3.a, < 4"
  - dependency-name: css-loader
    versions:
    - ">= 4.a, < 5"
  - dependency-name: css-loader
    versions:
    - ">= 5.a, < 6"
  - dependency-name: file-loader
    versions:
    - ">= 6.2.a, < 6.3"
  - dependency-name: react-responsive-modal
    versions:
    - ">= 5.a, < 6"
  - dependency-name: react-router
    versions:
    - ">= 4.a, < 5"
  - dependency-name: react-router
    versions:
    - ">= 5.a, < 6"
  - dependency-name: redis
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@shopify/polaris"
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@shopify/polaris"
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@shopify/shopify-express"
    versions:
    - "> 1.0.0.pre.alpha.7, < 1.0.1"
  - dependency-name: webpack
    versions:
    - ">= 4.a, < 5"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: shopify-api-node
    versions:
    - 3.6.1
    - 3.6.10
    - 3.6.2
    - 3.6.3
    - 3.6.4
    - 3.6.5
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
