version: "2"
services:
  nginx-qa:
    image: nginx:alpine
    restart: always
    ports:
      - 4433:443
    links:
      - app-qa
    networks:
      - app-qa
    volumes:
      - ./nginx:/work
      - ${SSL_CERT_PATH}:/etc/nginx/cert # Define this as an environment variable in Docker in host
    command: /bin/sh -c "envsubst < /work/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      - APP_HOST_NAME=app-qa
      - DOLLAR=$$
  redis-qa:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis-qa
    networks:
      - redis-net-qa
    volumes:
      - redis-data-qa:/data
  app-qa:
    image: dopplerdev/doppler-for-shopify-qa
    environment:
      - NODE_ENV=production
      - SHOPIFY_APP_HOST=https://sfy.fromdoppler.com:4433
      - SHOPIFY_APP_KEY=db82af6aa301fb2221ee70570227f14e
      - SHOPIFY_APP_SECRET=${SHOPIFY_APP_SECRET_QA} # Define this as an environment variable in Docker in host
      - SHOPIFY_APP_PORT=3000
      - SHOPIFY_APP_STORAGE_ENGINE=memory
      - REDIS_HOST=redis-qa
      - REDIS_PORT=6379
    expose:
      - "3000"
    networks:
      - redis-net-qa
      - app-qa
    depends_on:
      - redis-qa
networks:
  redis-net-qa:
  app-qa:

volumes:
  redis-data-qa:
