version: "2"
services:
  nginx-dev:
    image: nginx:alpine
    restart: always
    ports:
      - 4444:443
    links:
      - app-dev
    networks:
      - app-dev
    volumes:
      - ./nginx:/work
      - ${SSL_CERT_PATH}:/etc/nginx/cert # Define this as an environment variable in Docker in host
    command: /bin/sh -c "envsubst < /work/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      - APP_HOST_NAME=app-dev
      - DOLLAR=$$
  redis-dev:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis-dev
    networks:
      - redis-net-dev
    volumes:
      - redis-data-dev:/data
  app-dev:
    image: dopplerdev/doppler-for-shopify-dev
    environment:
      - NODE_ENV=production
      - SHOPIFY_APP_HOST=https://sfy.fromdoppler.com:4444
      - SHOPIFY_APP_KEY=480cde0c506309c5f6960d49dc6e4d7e
      - SHOPIFY_APP_SECRET=${SHOPIFY_APP_SECRET_DEV} # Define this as an environment variable in Docker in host
      - SHOPIFY_APP_PORT=3000
      - SHOPIFY_APP_STORAGE_ENGINE=memory
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
    expose:
      - "3000"
    networks:
      - redis-net-dev
      - app-dev
    depends_on:
      - redis-dev
networks:
  redis-net-dev:
  app-dev:

volumes:
  redis-data-dev:
