version: "3"
services:
  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  app:
    image: node:8-alpine
    working_dir: /work
    command: >
      /bin/sh -c "
      yarn install 
      && yarn run dev;
      "
    environment:
      - NODE_ENV=development
      - RHOST=redis
      - SHOPIFY_APP_HOST=http://localhost
      - SHOPIFY_APP_KEY=ab60395f0cef794b959ac302f52f28e2
      - SHOPIFY_APP_SECRET # Define this as an environment variable in Docker in host
      - SHOPIFY_APP_PORT=3000
      - SHOPIFY_APP_STORAGE_ENGINE=memory
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    networks:
      - redis-net
    depends_on:
      - redis
    volumes:
      - .:/work

networks:
  redis-net:

volumes:
  redis-data:
