version: "2"
services:
  nginx:
    image: dopplerdev/doppler-for-shopify-nginx
    ports:
      - 443:443
    links:
      - app
    networks:
      - app
    volumes:
      - ${SSL_CERT_PATH}:/etc/nginx/cert # Define this as an environment variable in Docker in host
  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  app:
    image: dopplerdev/doppler-for-shopify
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=production
      - SHOPIFY_APP_HOST=https://shopify.fromdoppler.com
      - SHOPIFY_APP_KEY=ab60395f0cef794b959ac302f52f28e2
      - SHOPIFY_APP_SECRET # Define this as an environment variable in Docker in host
      - SHOPIFY_APP_PORT=3000
      - SHOPIFY_APP_STORAGE_ENGINE=memory
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    networks:
      - redis-net
      - app
    depends_on:
      - redis
networks:
  redis-net:
  app:

volumes:
  redis-data:
