export const CONNECTING_TO_DOPPLER = 'CONNECTING_TO_DOPPLER';
export const CHANGE_DOPPLER_CREDENTIALS_STATUS = 'CHANGE_DOPPLER_CREDENTIALS_STATUS';
export const SHOW_ERROR_BANNER = 'SHOW_ERROR_BANNER';