export const CONNECTING_TO_DOPPLER = 'CONNECTING_TO_DOPPLER';
export const CHANGE_DOPPLER_CREDENTIALS_STATUS = 'CHANGE_DOPPLER_CREDENTIALS_STATUS';

export const RETRIEVING_DOPPLER_LISTS = 'RETRIEVING_DOPPLER_LISTS';
export const DOPPLER_LISTS_RETRIEVED = 'DOPPLER_LISTS_RETRIEVED';
export const CURRENT_SELECTED_LIST_CHANGED = 'CURRENT_SELECTED_LIST_CHANGED';
export const REQUEST_LIST_CREATION = 'REQUEST_LIST_CREATION';
export const CREATING_DOPPLER_LIST = 'CREATING_DOPPLER_LIST';
export const DUPLICATED_LIST_NAME = 'DUPLICATED_LIST_NAME';
export const DOPPLER_LIST_CREATED = 'DOPPLER_LIST_CREATED';
export const SETTING_DOPPLER_LIST = 'SETTING_DOPPLER_LIST';
export const LIST_SET = 'LIST_SET';

export const RETRIEVING_FIELDS = 'RETRIEVING_FIELDS';
export const FIELDS_RETRIEVED = 'FIELDS_RETRIEVED';
export const REQUESTING_FIELD_MAPPING_UPSERT = 'REQUESTING_FIELD_MAPPING_UPSERT';
export const REQUESTING_REMOVE_MAPPED_FIELD = 'REQUESTING_REMOVE_MAPPED_FIELD';
export const MAPPED_FIELD_REMOVED = 'MAPPED_FIELD_REMOVED';
export const NEW_MAPPED_FIELD_ADDED = 'NEW_MAPPED_FIELD_ADDED';
export const SETTING_FIELDS_MAPPING = 'SETTING_FIELDS_MAPPING';

export const SETUP_COMPLETED = 'SETUP_COMPLETED';
export const SYNCHRONIZATION_IN_PROGRESS = 'SYNCHRONIZATION_IN_PROGRESS';
export const REQUESTING_SYNCHRONIZATION = 'REQUESTING_SYNCHRONIZATION';

export const SHOW_ERROR_BANNER = 'SHOW_ERROR_BANNER';
