export const CONNECTING_TO_DOPPLER = 'CONNECTING_TO_DOPPLER';
export const CHANGE_DOPPLER_CREDENTIALS_STATUS = 'CHANGE_DOPPLER_CREDENTIALS_STATUS';

export const RETRIEVING_DOPPLER_LISTS = 'RETRIEVING_DOPPLER_LISTS';
export const DOPPLER_LISTS_RETRIEVED = 'DOPPLER_LISTS_RETRIEVED';
export const CURRENT_SELECTED_LIST_CHANGED = 'CURRENT_SELECTED_LIST_CHANGED';
export const REQUEST_LIST_CREATION = 'REQUEST_LIST_CREATION';
export const CREATING_DOPPLER_LIST = 'CREATING_DOPPLER_LIST';
export const DUPLICATED_LIST_NAME = 'DUPLICATED_LIST_NAME';
export const DOPPLER_LIST_CREATED = 'DOPPLER_LIST_CREATED';
export const SETTING_DOPPLER_LIST = 'SETTING_DOPPLER_LIST';

export const SHOW_ERROR_BANNER = 'SHOW_ERROR_BANNER';